In [3]:
# Pandas es una biblioteca de Python utilizada para trabajar con conjuntos de datos.
# Tiene funciones de análisis, limpieza, exploración y manipulación de datos.
import pandas as pd

In [4]:
# Cargar un archivo CSV en un DataFrame de Pandas
df = pd.read_csv("Masacres_en_Colombia.csv")

In [5]:
# Devuelve el valor de N° de Filas y N° de Columnas
df.shape

(301, 8)

In [6]:
# El DataFrames permite visualizar información detallada del data set
df.info

<bound method DataFrame.info of                 FECHA HECHO  COD_DEPTO     DEPARTAMENTO  COD_MUNI  \
0    01/02/2022 12:00:00 AM         81           ARAUCA     81300   
1    01/03/2022 12:00:00 AM         76  VALLE DEL CAUCA     76364   
2    01/06/2022 12:00:00 AM         85         CASANARE     85139   
3    01/08/2022 12:00:00 AM         47        MAGDALENA     47980   
4    01/08/2022 12:00:00 AM         52           NARIÑO     52203   
..                      ...        ...              ...       ...   
296  03/18/2025 12:00:00 AM          5        ANTIOQUIA      5034   
297  04/19/2025 12:00:00 AM         76  VALLE DEL CAUCA     76834   
298  04/20/2025 12:00:00 AM         13          BOLIVAR     13001   
299  04/27/2025 12:00:00 AM         95         GUAVIARE     95001   
300  04/28/2025 12:00:00 AM         50             META     50568   

                 MUNICIPIO  ZONA  CASOS  VICTIMAS  
0                   FORTUL   NaN      1         4  
1                  JAMUNDI   NaN   

In [7]:
df

FECHA HECHO  COD_DEPTO     DEPARTAMENTO  COD_MUNI  \
0    01/02/2022 12:00:00 AM         81           ARAUCA     81300   
1    01/03/2022 12:00:00 AM         76  VALLE DEL CAUCA     76364   
2    01/06/2022 12:00:00 AM         85         CASANARE     85139   
3    01/08/2022 12:00:00 AM         47        MAGDALENA     47980   
4    01/08/2022 12:00:00 AM         52           NARIÑO     52203   
..                      ...        ...              ...       ...   
296  03/18/2025 12:00:00 AM          5        ANTIOQUIA      5034   
297  04/19/2025 12:00:00 AM         76  VALLE DEL CAUCA     76834   
298  04/20/2025 12:00:00 AM         13          BOLIVAR     13001   
299  04/27/2025 12:00:00 AM         95         GUAVIARE     95001   
300  04/28/2025 12:00:00 AM         50             META     50568   

                 MUNICIPIO  ZONA  CASOS  VICTIMAS  
0                   FORTUL   NaN      1         4  
1                  JAMUNDI   NaN      1         3  
2                     MANI   NaN      1         3  
3            ZONA BANANERA   NaN      1         3  
4                    COLON   NaN      1         3  
..                     ...   ...    ...       ...  
296                  ANDES   NaN      1         4  
297                  TULUA   NaN      1         3  
298    CARTAGENA DE INDIAS   NaN      1         3  
299  SAN JOSE DEL GUAVIARE   NaN      1         7  
300          PUERTO GAITAN   NaN      1         4  

[301 rows x 8 columns]

In [8]:
# Visualiza los nombres de los encabezados
df.columns

Index(['FECHA HECHO', 'COD_DEPTO', 'DEPARTAMENTO', 'COD_MUNI', 'MUNICIPIO',
       'ZONA', 'CASOS', 'VICTIMAS'],
      dtype='object')

In [9]:
# Devuelve los encabezados y un número específico de filas, comenzando desde la fila 0
df.head(5)

FECHA HECHO  COD_DEPTO     DEPARTAMENTO  COD_MUNI  \
0  01/02/2022 12:00:00 AM         81           ARAUCA     81300   
1  01/03/2022 12:00:00 AM         76  VALLE DEL CAUCA     76364   
2  01/06/2022 12:00:00 AM         85         CASANARE     85139   
3  01/08/2022 12:00:00 AM         47        MAGDALENA     47980   
4  01/08/2022 12:00:00 AM         52           NARIÑO     52203   

       MUNICIPIO  ZONA  CASOS  VICTIMAS  
0         FORTUL   NaN      1         4  
1        JAMUNDI   NaN      1         3  
2           MANI   NaN      1         3  
3  ZONA BANANERA   NaN      1         3  
4          COLON   NaN      1         3

In [10]:
# tail() muestra las últimas filas del DataFrame y por defecto 5 si no se especifica el #; NaN indica valores faltantes.
df.tail(4)

FECHA HECHO  COD_DEPTO     DEPARTAMENTO  COD_MUNI  \
297  04/19/2025 12:00:00 AM         76  VALLE DEL CAUCA     76834   
298  04/20/2025 12:00:00 AM         13          BOLIVAR     13001   
299  04/27/2025 12:00:00 AM         95         GUAVIARE     95001   
300  04/28/2025 12:00:00 AM         50             META     50568   

                 MUNICIPIO  ZONA  CASOS  VICTIMAS  
297                  TULUA   NaN      1         3  
298    CARTAGENA DE INDIAS   NaN      1         3  
299  SAN JOSE DEL GUAVIARE   NaN      1         7  
300          PUERTO GAITAN   NaN      1         4

In [11]:
# loc permite acceder a filas por índice; por ejemplo, loc[0] devuelve la primera fila.
df.loc[0]

FECHA HECHO     01/02/2022 12:00:00 AM
COD_DEPTO                           81
DEPARTAMENTO                    ARAUCA
COD_MUNI                         81300
MUNICIPIO                       FORTUL
ZONA                               NaN
CASOS                                1
VICTIMAS                             4
Name: 0, dtype: object

In [14]:
# describe() genera estadísticas descriptivas de cada columna numérica.
df.COD_DEPTO.describe()


count    301.000000
mean      39.893688
std       28.595372
min        5.000000
25%       13.000000
50%       41.000000
75%       68.000000
max       95.000000
Name: COD_DEPTO, dtype: float64

In [16]:
df.COD_MUNI.describe()


count      301.000000
mean     40212.687708
std      28611.011324
min       5001.000000
25%      13001.000000
50%      41020.000000
75%      68190.000000
max      95001.000000
Name: COD_MUNI, dtype: float64

In [15]:
df["DEPARTAMENTO"].describe()

count       301
unique       28
top       CAUCA
freq         36
Name: DEPARTAMENTO, dtype: object

In [17]:
df["MUNICIPIO"].describe()

count             301
unique            170
top       BOGOTA D.C.
freq               16
Name: MUNICIPIO, dtype: object

In [20]:
df.ZONA.describe()


count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: ZONA, dtype: float64

In [21]:
df.VICTIMAS.describe()


count    301.000000
mean       3.488372
std        1.215469
min        3.000000
25%        3.000000
50%        3.000000
75%        4.000000
max       18.000000
Name: VICTIMAS, dtype: float64

In [ ]:
# Conteo de Victimas
df.VICTIMAS.count()


np.int64(301)

In [ ]:
# Promedio de Victimas
df.VICTIMAS.mean()

np.float64(3.488372093023256)

In [ ]:
# Desviación Estándar de Victimas 
df.VICTIMAS.std()

np.float64(1.2154687742123493)

In [ ]:
# Valor Mínimo de Victimas 
df.VICTIMAS.min()


np.int64(3)

In [ ]:
# Valor Máximo de Victimas 
df.VICTIMAS.max()

np.int64(18)

In [27]:
# Mediana de Victimas
df.VICTIMAS.median()

np.float64(3.0)

In [28]:
# Obtener valores unicos de cada criterio
df.ZONA.unique()

array([nan])

In [30]:
# Obtener valores unicos de cada criterio
df.VICTIMAS.unique()

array([ 4,  3,  7,  5,  6, 18, 10])

In [31]:
# Obtener valores unicos de cada criterio
df.COD_DEPTO.unique()

array([81, 76, 85, 47, 52, 86,  5, 19, 91, 11, 13, 50, 25,  8, 73, 20, 18,
       70, 54, 41, 68, 66, 44, 23, 15, 27, 95, 17])

In [32]:
# Obtener valores unicos de cada criterio
df.COD_MUNI.unique()

array([81300, 76364, 85139, 47980, 52203, 86571,  5690, 19110,  5038,
       86573, 81065,  5604, 81736, 91001, 47001,  5861,  5001, 11001,
       76243, 76111,  5154, 13001,  5361, 50370, 81794, 19075,  5284,
       25645, 76147, 19100,  8001, 73168, 20238, 18150, 52835,  5642,
       18410, 19698,  8758, 18592, 70001, 20400, 19450, 52079, 76400,
       19473, 19256, 47288, 76823, 18256,  5250, 52227, 54001, 52427,
       41001, 68385, 50577, 86569, 76001, 66383, 19622, 70713, 19130,
       86568, 19050, 18785, 50568, 86320, 20614, 44001, 52356,  5615,
       47245,  5101, 23678,  5134, 47189, 73268, 54405, 15293, 52256,
       54245, 27600, 44090, 47460, 41298, 18001, 86865, 54810, 95001,
       86885, 19548, 20787,  8573, 50001, 27001, 19212, 76834, 27077,
       41357,  5120, 66682, 86001, 13433, 50689, 13836, 20001,  5002,
       19142,  8433, 23807,  5088, 19455, 52254, 76828,  5579, 85440,
       76109, 76520,  5042, 17380, 25473, 76130, 13473, 41551, 85125,
       76041, 66687,

In [33]:
# Obtener valores unicos de cada criterio
df["DEPARTAMENTO"].unique()

array(['ARAUCA', 'VALLE DEL CAUCA', 'CASANARE', 'MAGDALENA', 'NARIÑO',
       'PUTUMAYO', 'ANTIOQUIA', 'CAUCA', 'AMAZONAS', 'BOGOTA D.C.',
       'BOLIVAR', 'META', 'CUNDINAMARCA', 'ATLANTICO', 'TOLIMA', 'CESAR',
       'CAQUETA', 'SUCRE', 'NORTE DE SANTANDER', 'HUILA', 'SANTANDER',
       'RISARALDA', 'LA GUAJIRA', 'CORDOBA', 'BOYACA', 'CHOCO',
       'GUAVIARE', 'CALDAS'], dtype=object)

In [34]:
# Obtener valores unicos de cada criterio
df["MUNICIPIO"].unique()

array(['FORTUL', 'JAMUNDI', 'MANI', 'ZONA BANANERA', 'COLON',
       'PUERTO GUZMAN', 'SANTO DOMINGO', 'BUENOS AIRES', 'ANGOSTURA',
       'LEGUIZAMO', 'ARAUQUITA', 'REMEDIOS', 'SARAVENA', 'LETICIA',
       'SANTA MARTA', 'VENECIA', 'MEDELLIN', 'BOGOTA D.C.', 'EL AGUILA',
       'GUADALAJARA DE BUGA', 'CAUCASIA', 'CARTAGENA', 'ITUANGO', 'URIBE',
       'TAME', 'BALBOA', 'FRONTINO', 'SAN ANTONIO DEL TEQUENDAMA',
       'CARTAGO', 'BOLIVAR', 'BARRANQUILLA', 'CHAPARRAL', 'EL COPEY',
       'CARTAGENA DEL CHAIRA', 'SAN ANDRES DE TUMACO', 'SALGAR',
       'LA MONTAÑITA', 'SANTANDER DE QUILICHAO', 'SOLEDAD', 'PUERTO RICO',
       'SINCELEJO', 'LA JAGUA DE IBIRICO', 'MERCADERES', 'BARBACOAS',
       'LA UNION', 'MORALES', 'EL TAMBO', 'FUNDACION', 'TORO',
       'EL PAUJIL', 'EL BAGRE', 'CUMBAL', 'CUCUTA', 'MAGUI', 'NEIVA',
       'LANDAZURI', 'PUERTO LLERAS', 'PUERTO CAICEDO', 'CALI', 'LA CELIA',
       'ROSAS', 'SAN ONOFRE', 'CAJIBIO', 'PUERTO ASIS', 'ARGELIA',
       'SOLITA', 'PUERTO GAITA